version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: sunday
      time: '09:00'
    commit-message:
      prefix: ".github/workflows"
