labels:
  - name: new/library
    description: Issues and PRs related to a new library
    color: "#7bdb48"

  - name: new/metric
    description: Issues and PRs related to a new metric
    color: "#7bdb48"

  - name: new/posix-function
    description: Issues and PRs related to a new POSIX function
    color: "#7bdb48"

  - name: new/primitive
    description: Issues and PRs related to a new primitive
    color: "#7bdb48"

  - name: new/syscall
    description: Issues and PRs related to a new syscall
    color: "#7bdb48"

  - name: new/test
    description: Issues and PRs related to a new test
    color: "#7bdb48"
